[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "fund-mithril-lib-siso-msdl"
version = "0.3.0"
requires-python = ">=3.11"
dependencies = ["fund-mithril-lib-interop @ git+https://github.com/mithril-lang/fund.mithril.lib.interop.git@8ec10c56678eb6508515e2eafdb41ace4866a654", "fund-mithril-lib-xml @ git+https://github.com/mithril-lang/fund.mithril.lib.xml.git@dc1fbf7d79367667c927166ce02dcd250cbab1c3"]

[project.entry-points."mithril.interop.plugins"]
"fund.mithril.lib.siso.msdl" = "mithril_msdl.plugin:Plugin"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.json", "*.xml"]
